"""
Django settings for taskflow project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.contrib.messages import constants as message_constants
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge les variables du fichier .env (non commité) dans os.environ.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Clé API OpenAI pour l'assistant IA (génération de tâches). Absente en test
# (l'appel OpenAI y est toujours mocké) ; requise en dev/prod pour l'endpoint.
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if host.strip()
]
# En prod serverless (Vercel), le domaine est *.vercel.app : on l'autorise
# toujours, en plus des hôtes fournis par l'environnement.
ALLOWED_HOSTS += ['.vercel.app']
if not ALLOWED_HOSTS or ALLOWED_HOSTS == ['.vercel.app']:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1']

# Django 4+ exige des origines de confiance pour les POST cross-origin en HTTPS
# (connexion, formulaires, fetch de l'assistant). On fait confiance au domaine
# Vercel et à toute origine fournie par l'environnement.
CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app'] + [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps tierces
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    # Apps locales
    'accounts',
    'projects',
    'tasks',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'taskflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taskflow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# En production, la base est fournie par une URL de connexion. Vercel Postgres
# expose plusieurs variables : on privilégie la connexion NON poolée (directe),
# adaptée à Django et aux migrations. En local (aucune URL), on retombe sur les
# variables DB_* du .env.
DATABASE_URL = (
    os.environ.get('DATABASE_URL')
    or os.environ.get('POSTGRES_URL_NON_POOLING')
    or os.environ.get('POSTGRES_URL')
)
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            # Serverless : pas de connexions persistantes entre invocations.
            conn_max_age=0,
            ssl_require=True,
        )
    }
else:
    # `.get` avec valeurs par défaut : `collectstatic` au build importe les
    # settings sans qu'une base soit forcément configurée ; il ne s'y connecte
    # pas, donc on évite un KeyError qui casserait le build. En local, les
    # variables DB_* du .env priment.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'taskflow'),
            'USER': os.environ.get('DB_USER', 'taskflow'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Le front est en français : les libellés, aides et messages fournis par Django
# et DRF (validateurs de mot de passe, erreurs de formulaire et d'API) sont
# traduits en conséquence.
LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# `collectstatic` (lancé au build Vercel par build_files.sh) rassemble les
# fichiers ici ; Vercel sert ce dossier via la route /static/ (cf. vercel.json).
STATIC_ROOT = BASE_DIR / 'staticfiles_build' / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Modèle utilisateur custom (voir accounts/models.py pour la justification).
AUTH_USER_MODEL = 'accounts.User'


# Authentification du front (session Django). Sans rapport avec l'API, qui reste
# en JWT seul (cf. core/SPEC-front-base.md §3).
LOGIN_URL = '/connexion/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/connexion/'

# Le tag Django pour une erreur est « error », mais la classe Bootstrap est
# « alert-danger » : sans cette table, messages.error() produirait un
# `alert-error` inexistant, donc une alerte non stylée.
MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}


# Django REST Framework : authentification par JWT (djangorestframework-simplejwt).
# On ne fixe pas de DEFAULT_PERMISSION_CLASSES global : les permissions sont
# gérées au niveau de chaque ViewSet (cf. skill drf-resource).
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}
